### ISSUE TITLE
Adding labels to a secret

### ISSUE THREAD

**Issue by nooshin-mirzadeh** [postfinance/vault-kubernetes#14]
Hi,
Thanks for this nice work. 
I am wondering is there a way to add a label to the secrets? It looks that we can add annotations, but not a label, am I right, or am I missing sth?

**Comment by marcsauter** [comment]
Hi,
What's your use case for labels? 
The annotation is to identify the secret as a secret from vault with corresponding path:
```
metadata:
  annotations:
    vault-secret: secret/team_linux/k8s/p1-k8s-management/appl-nightwatch-t1/nightwatch

```

**Comment by nooshin-mirzadeh** [comment]
This is useful for working with operators for us. There are some operators need some secrets to be set for them with a specific labels (otherwise, they cannot find them). We would like to share the secret from vault with the label. (If we set the label manually, and run the sync job again, it overwrites the label to none)
