### ISSUE TITLE
Authentication Failed when trying to sync

### ISSUE THREAD

**Issue by terraform-class** [postfinance/vault-kubernetes#15]
2021/01/22 02:30:13 authentication failed - ALLOW_FAIL is set therefore pod will continue: login failed with role from environment variable VAULT_ROLE: "vault-role-stagingv3": Error making API request.

URL: PUT https://vault.gravitysupplychain.local:8200/v1/auth/stagingv3-terraform-aks/login
Code: 500. Errors:

* {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"tokenreviews.authentication.k8s.io is forbidden: User \"system:serviceaccount:default:vault-serviceaccount\" cannot create resource \"tokenreviews\" in API group \"authentication.k8s.io\" at the cluster scope","reason":"Forbidden","details":{"group":"authentication.k8s.io","kind":"tokenreviews"},"code":403}

**Comment by zbindenren** [comment]
You need to give access to the token review api as described here: https://www.vaultproject.io/docs/auth/kubernetes#configuring-kubernetes.

**Comment by terraform-class** [comment]
I checked all the rbac roles and they are the same ones I have been using for almost 2 years. Re-Applied from your link also. No change

**Comment by terraform-class** [comment]
I forgot to add the service account back into my terraform code. Thanks for your help

**Comment by zbindenren** [comment]
No problem.
