### ISSUE TITLE
Feature request: other secret engines

### ISSUE THREAD

**Issue by cpick** [postfinance/vault-kubernetes#7]
Thanks for releasing this set of images.

I would love to be able to use them, but my use case requires fetching a secret from a different engine (specifically a GCP key from "gcp/key/foo-roleset") which would require support for a read request from the "gcp" secret engine (and possibly a base64 decode of the resulting value).

Would you consider adding such a feature to the synchronizer?
Thanks again, -Chris

**Comment by ghouscht** [comment]
Hi Chris,
I'm sorry to disappoint you but this is currently not in our scope. 
Regards, Thomas
