### ISSUE TITLE
More tags on Docker Hub

### ISSUE THREAD

**Issue by rafis** [postfinance/vault-kubernetes#8]
There is currently only `latest` tag on Docker Hub. Please add more tags on Docker Hub so that we can prevent issues with transitition from one version to incompatible new versions.

**Comment by djboris9** [comment]
Hi rafis

Thanks for the hint. We haven't tagged our repository for a longer time so there were no tagged Docker images with recent commits available.

Now the latest commit is tagged and you can use the newly published images with label "0.1.3" e.g. `postfinance/vault-kubernetes-synchronizer:0.1.13`

**Comment by djboris9** [comment]
Closing the issue now. If there are any questions or suggestions, feel free to reopen it.
